### ISSUE TITLE
Assertion failed: Exit events not matched by an enter

### ISSUE THREAD

**Issue by samreid** [phetsims/hookes-law#18] opened 2015-08-11 05:37 UTC
Most likely a scenery issue but I saw this in Hooke's Law so I'll report here first.  With the dev tools open, if I open the Systems screen and move the slider, then mouse out and back in, I see this problem.  It happened 2-3 times in a row so I thought I should report it:

> Uncaught Error: Assertion failed: Exit events not matched by an enter

![image](https://cloud.githubusercontent.com/assets/679486/9190903/659c9ed0-3fb8-11e5-832e-fd926e3e670c.png)

I'll reassign to @pixelzoom to see if he can reproduce the problem.

I'm on OSX 10.10.4 running Chrome Version 44.0.2403.130 (64-bit).  Testing a requirejs version of hookes law out of master.  Tagging @jonathanolson in case he knows anything helpful about this kind of error.

**Comment by samreid** [comment] 2015-08-11 05:39
This error happened again on the next run (4th run) but not the following 2 runs.

**Comment by pixelzoom** [comment] 2015-08-11 17:34
Thanks for reproducing this. I've seen it a few times (over the past few months?). I couldn't reproduce it, so assumed (perhaps incorrectly) that it was transient Chrome problem.  No idea what the cause is, so assigning to @jonathanolson.  If this is indeed a scenery issue, then it's probably high priority.

**Comment by pixelzoom** [comment] 2015-08-12 18:40
@samreid There's no URL shown in your screenshot, and you didn't mention how you were running the sim.  But I'm assuming you were running with assertions enabled (?ea), correct?

**Comment by samreid** [comment] 2015-08-12 18:43
Yes, ?ea

**Comment by samreid** [comment] 2015-08-12 18:44
You can see that it says enabling assert in the console

**Comment by jonathanolson** [comment] 2015-08-13 06:04
I've spent about 15-20 minutes trying to reproduce across platforms (I have OS X 10.9.5, maybe that is a difference), for OS X, Windows and all browsers, and I haven't been able to cause it.

Any more detail on:

> open the Systems screen and move the slider, then mouse out and back in

Mouse out (of window?)

**Comment by samreid** [comment] 2015-08-13 14:27
I tested with the built and non-built versions of hookes law and could not reproduce the problem again.

**Comment by samreid** [comment] 2015-08-13 14:27
Not sure what else I can do here, I'll send it back to @pixelzoom to decide what's next, if anything.

**Comment by pixelzoom** [comment] 2015-08-13 16:44
Hmmm... Now I can't reproduce reliably either.  But I have seen this repeatedly with hookes-law and other sims over the past few months.  So I'm hesitant to just close this as "cannot reproduce".

Searching for the error message, this assertion comes from `scenery.ButtonListener`, line 104:

`assert && assert( this._overCount > 0, 'Exit events not matched by an enter' );`

@jonathanolson Does that provide any additional clues about what might be going on here, or how to reproduce it reliably?

**Comment by jonathanolson** [comment] 2015-08-13 21:24
Yes, it would generally indicate an inconsistent state for input handling. It could be either a browser issue or Scenery issue.

It's the type of bug where it would be very helpful to record Scenery input events so that we could play back the failing sequence once recorded.

**Comment by samreid** [comment] 2015-08-14 02:10
In my case, I was mousing out to the dev tools, not out of the entire browser.  Not sure if that was a critical ingredient or not.

**Comment by jonathanolson** [comment] 2015-08-14 02:49
> In my case, I was mousing out to the dev tools, not out of the entire browser. Not sure if that was a critical ingredient or not.

That's what I was testing. Just tried it out a few more times on OS X / Win, and still wasn't able to reproduce. If we can reproduce even somewhat regularly, I think it would be useful to log all input events.

I'll leave assigned to me, and look more into bringing Scenery event recording back up-to-date.

**Comment by jonathanolson** [comment] 2015-08-14 04:29
Pulling latest. If you're able to reproduce, please do the following:
1. In 'chronicle', npm install
2. In 'chronicle', node js/server.js
3. Run sim with ?recordInputEventLog&ea
4. If assertion is hit, resume, interact just a bit more, then close the sim browser tab (it uses a websocket, but the message won't be hit right when the debugger pauses it).
5. Check chronicle/data for a .txt file, and get it to me.
6. Record exact SHAs, to help reproduce?

I'll hopefully be able to reproduce from a log.

**Comment by pixelzoom** [comment] 2015-08-18 21:33
I've been playing around with the sim, but can't reproduce the problem. Mac OS X 10.10.5, Chrome 4.0.2403.155 (64 bit).

@samreid you said:

> With the dev tools open, if I open the Systems screen and move the slider, then mouse out and back in, I see this problem.

Do you recall if you moved into the dev tools window with the mouse still down on the slider? Or did you release the mouse in the browser window, then move the mouse (still up) into the dev tools window?

**Comment by samreid** [comment] 2015-08-18 22:08
I believe the mouse was up, but, like I said in https://github.com/phetsims/hookes-law/issues/18#issuecomment-130695248 I can no longer reproduce the problem.

**Comment by pixelzoom** [comment] 2015-08-24 15:16
As I mentioned in https://github.com/phetsims/hookes-law/issues/18#issuecomment-130754603, this assertion is occurring in `scenery.ButtonListener`.  So it seems like we should be able to isolate it, or at least hypothesize about what's causing it.  But I've been unable to reproduce it, and I haven't heard any thoughts about how this might be related to `scenery.ButtonListener`.  So I'm going to unassign this issue. If someone experiences the problem, follow @jonathanolson's instructions in https://github.com/phetsims/hookes-law/issues/18#issuecomment-130961341.

**Comment by pixelzoom** [comment] 2015-08-24 15:24
This is a general issue, moved to https://github.com/phetsims/scenery/issues/456.

**Closed as completed by pixelzoom** 2015-08-24 15:24 UTC
Labels: type:bug, priority:2-high
