### ISSUE TITLE
Scenery iframe issue still exists

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/hookes-law#32] opened 2015-10-15 18:07 UTC
Test device: Personal 

Operating System: iOS 10.10.5

Browser: Safari 9.0 (10601.1.56.2)

Problem description: phetsims/scenery#464 appears to still be present.  

Steps to reproduce: Open iFrame. Click and hold down mouse on either slider. While still holding down mouse, move the mouse outside of the iFrame. Release the mouse button. Moving the mouse outside the iFrame will not trigger anything, but once the mouse is moved inside the iFrame the slider will move without the mouse being clicked. The mouse must be clicked in order for the slider to be released. It may take a few tries to reproduce this issue.

Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Molarity‬
URL: http://www.colorado.edu/physics/phet/dev/html/molarity/1.2.0-rc.2/molarity_en.html
Version: 1.2.0-rc.2 2015-10-14 21:49:07 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x662
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.6.33)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"master"},"axon":{"sha":"e2237347","branch":"master"},"babel":{"sha":"931afbf1","branch":"master"},"brand":{"sha":"8a756e53","branch":"master"},"chipper":{"sha":"157b9cf3","branch":"master"},"dot":{"sha":"d99cbe46","branch":"master"},"joist":{"sha":"121bb0de","branch":"master"},"kite":{"sha":"40dc703a","branch":"master"},"molarity":{"sha":"515f4f2f","branch":"1.2"},"nitroglycerin":{"sha":"88cfd142","branch":"master"},"phet-core":{"sha":"e9f36af1","branch":"master"},"phetcommon":{"sha":"0e4754fe","branch":"master"},"scenery":{"sha":"c1d6232d","branch":"master"},"scenery-phet":{"sha":"88ade507","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"b66398a5","branch":"master"},"tandem":{"sha":"c54f1082","branch":"master"}}

**Comment by pixelzoom** [comment] 2015-10-15 18:18
@elisemorgan wrote:

> Operating System: iOS 10.10.5

Do you mean OS X 10.10.5 ?

**Comment by jonathanolson** [comment] 2015-10-15 18:27
Unable to reproduce on OS X 10.9.5 with Safari 7.1.8. Anyone with a better-matching platform able to test?

> Do you mean OS X 10.10.5 ?

Looks like it, notes that version in the user agent string.

Name: ‪Molarity‬
URL: http://www.colorado.edu/physics/phet/dev/html/molarity/1.2.0-rc.2/molarity_en.html
Version: 1.2.0-rc.2 2015-10-14 21:49:07 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/7.1.8 Safari/537.85.17
Language: en-us
Window: 1366x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.28.32)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"master"},"axon":{"sha":"e2237347","branch":"master"},"babel":{"sha":"931afbf1","branch":"master"},"brand":{"sha":"8a756e53","branch":"master"},"chipper":{"sha":"157b9cf3","branch":"master"},"dot":{"sha":"d99cbe46","branch":"master"},"joist":{"sha":"121bb0de","branch":"master"},"kite":{"sha":"40dc703a","branch":"master"},"molarity":{"sha":"515f4f2f","branch":"1.2"},"nitroglycerin":{"sha":"88cfd142","branch":"master"},"phet-core":{"sha":"e9f36af1","branch":"master"},"phetcommon":{"sha":"0e4754fe","branch":"master"},"scenery":{"sha":"c1d6232d","branch":"master"},"scenery-phet":{"sha":"88ade507","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"b66398a5","branch":"master"},"tandem":{"sha":"c54f1082","branch":"master"}}

**Comment by pixelzoom** [comment] 2015-10-15 18:35
Dev meeting decision:  We're going to publish with this known problem, because it's better than what's on the website now.  phetsims/scenery#464 will remain open to track the general issue.

Closing.

**Closed as completed by pixelzoom** 2015-10-15 18:35 UTC
