### ISSUE TITLE
robotic arm resizes when interacting (Firefox Win7)

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/hookes-law#19] opened 2015-08-12 23:54 UTC
When I try interacting with the robot arm (clicking and moving back and forth) the box from which the arm is coming out of appears to grow and shrink slightly. Does not happen on chrome.

Test device: Dell Desktop

Operating System: Win 7 

Browser: FF 40.0

Problem description:

Steps to reproduce:

Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Hooke's Law‬
URL: http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-dev.27/hookes-law_en.html
Version: 1.0.0-dev.27 2015-08-12 18:26:02 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
Language: en-US
Window: 1920x943
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"1f0ca9f4","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"aa39bc48","branch":"master"},"chipper":{"sha":"f8c577e6","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"hookes-law":{"sha":"99de18ed","branch":"master"},"joist":{"sha":"77298536","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"89a44d2c","branch":"master"},"scenery":{"sha":"3a136ff1","branch":"master"},"scenery-phet":{"sha":"6c8a2423","branch":"master"},"sherpa":{"sha":"4f160877","branch":"master"},"sun":{"sha":"66c091cc","branch":"master"}}

**Comment by pixelzoom** [comment] 2015-08-13 00:00
Reminder to self: Have @ariel-phet demonstrate this to me at tomorrow's status meeting.

**Comment by pixelzoom** [comment] 2015-08-13 00:06
I tested with FF 36.0 on Mac OS X 10.10.4 and saw no problem.  Then I upgrade to FF 40.0.  I didn't see the problem that @ariel-phet described, but found this new issue: https://github.com/phetsims/scenery/issues/451.

**Comment by pixelzoom** [comment] 2015-08-13 00:09
Similar odd lines in the cuvette (Cuvette.js) in the "Beer's Law" screen of beers-law-lab. FF 40.0 on Mac OS 10.10.4, running with master in requirejs mode.

![screenshot_66](https://cloud.githubusercontent.com/assets/3046552/9239875/41564722-411d-11e5-9bea-93ce19d3c9b9.png)

**Comment by pixelzoom** [comment] 2015-08-13 16:53
@ariel-phet couldn't reproduce this with FF 40.0 on Win 8.

**Comment by pixelzoom** [comment] 2015-08-13 17:13
I reproduced this with FF 35.0 + Win 7 on VMWare.  Checking through old dev versions, it's first reproducible in 1.0.0-dev.25 (7/16/2015).

After upgrading to FF 40.0, I can't reproduce the problem. But a new problem occurs - while dragging the "hand" or sliders,  the horizontal piece of the arm (as it changes length) shifts up slightly and it's top edge get fuzzy.

**Comment by pixelzoom** [comment] 2015-08-13 17:26
The problem is resolution dependent. After resizing the browser window, I was able to reproduce what @ariel-phet described on FF 44.0 + Win 7, as well as the issue mentioned immediately above. 

According to @jonathanolson, these problems are caused by a known issue: FF uses lower quality rendering while things are moving (see phetsims/scenery#47).

As a workaround, try using renderer:'canvas' for RoboticArmNode.

**Comment by pixelzoom** [comment] 2015-08-25 20:51
I experimented with `renderer:'canvas'` for RoboticArmNode, and it does indeed eliminate this problem. But it creates a new problem (https://github.com/phetsims/hookes-law/issues/21#issuecomment-134735734): The arm and right "wall" jiggle like crazy while dragging the hand.

**Comment by pixelzoom** [comment] 2015-08-25 20:52
I experimented with `renderer:'canvas'` for RoboticArmNode, and it does indeed eliminate this problem.

But 2 things:

(1) It creates a new problem (https://github.com/phetsims/hookes-law/issues/21#issuecomment-134735734): The arm and right "wall" jiggle like crazy while dragging the hand.

(2) I don't know what impact it has on the structure (and performance) of the HTML document.

**Comment by pixelzoom** [comment] 2015-08-25 21:08
@ariel-phet Working around this on FF+Win7 causes a problem that's even worse on FF+Mac (see https://github.com/phetsims/hookes-law/issues/21#issuecomment-134735734).  

This issue is not specific to hookes-law.  So my recommendation is live with it for the 1.0.0 release, close this issue, continue track it in https://github.com/phetsims/scenery/issues/47, and (if it's really important) focus on submitting a reproducible example to Mozilla.

Let me know how you'd like me to proceed.

**Comment by pixelzoom** [comment] 2015-08-27 21:37
@ariel-phet asked me to close this as 'won't fix'.  We'll wait for Mozilla to fix.

**Closed as completed by pixelzoom** 2015-08-27 21:37 UTC
Labels: type:wontfix
