### ISSUE TITLE
black box appears behind spring (Firefox)

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/hookes-law#33] opened 2015-10-16 14:30 UTC
Test device: Dell Laptop

Operating System: Windows 10

Browser: Firefox 41.0.2

Problem description: Noticed that a black box appears behind the springs when I move the spring constant slider for the left spring. I have been unable to reproduce this issue with other sliders or in other browsers thus far.

Steps to reproduce: Go to systems screen, select springs in parallel. Drag spring constant slider for left spring back and forth. 

Severity:

Screenshots: 
![img_7283](https://cloud.githubusercontent.com/assets/12610678/10544312/7ea98156-73d7-11e5-968e-d4aba89216dc.JPG)

Troubleshooting information (do not edit):
Name: ‪Hooke's Law‬
URL: http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-rc.2/hookes-law_en.html
Version: 1.0.0-rc.2 2015-10-15 15:26:39 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
Language: en-US
Window: 1536x755
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"master"},"axon":{"sha":"e2237347","branch":"master"},"babel":{"sha":"931afbf1","branch":"master"},"brand":{"sha":"8a756e53","branch":"master"},"chipper":{"sha":"157b9cf3","branch":"master"},"dot":{"sha":"d99cbe46","branch":"master"},"hookes-law":{"sha":"dce3e4bb","branch":"1.0"},"joist":{"sha":"121bb0de","branch":"master"},"kite":{"sha":"40dc703a","branch":"master"},"phet-core":{"sha":"e9f36af1","branch":"master"},"phetcommon":{"sha":"0e4754fe","branch":"master"},"scenery":{"sha":"c1d6232d","branch":"master"},"scenery-phet":{"sha":"88ade507","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"b66398a5","branch":"master"},"tandem":{"sha":"c54f1082","branch":"master"}}

**Comment by ariel-phet** [comment] 2015-10-16 16:24
@bryo5363 can you try to reproduce this bug on your machine (make sure you have the latest version of FF)

I am not seeing this issue on Win 7, will also check Win 8.

**Comment by ariel-phet** [comment] 2015-10-16 16:53
Not able to produce on Win 8, FF 41.0.2 (same browser version)

@elisemorgan does this still occur if none of the options are checked (displacement, etc)? Or do certain checkboxes need to be checked to see the bug?

**Comment by elisemorgan** [comment] 2015-10-16 16:59
Occurs when equilibrium position and force arrows are checked. There must
be an applied force so that the spring is moving back and forth.

**Comment by jonathanolson** [comment] 2015-10-16 17:51
I'm able to reproduce on a Win10 VM. It also seems somewhat screen-size specific (if the window is smaller it doesn't seem to happen). Was a bit tricky to get it to happen the first time.

Additionally, it seems I need to resize or somehow get things repositioned, and THEN drag. It will occur a few times, and then won't occur again until I resize the window again.

I haven't been able to snag a screenshot, but sometimes it isn't a perfect black rectangle. Sometimes the edges are a bit sheared.

Assigning to myself for investigation. @ariel-phet or @pixelzoom, is this a blocking issue for the sim?

Name: ‪Hooke's Law‬
URL: http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-rc.2/hookes-law_en.html
Version: 1.0.0-rc.2 2015-10-15 15:26:39 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
Language: en-US
Window: 1075x680
Pixel Ratio: 1/1
WebGL: disabled

**Comment by ariel-phet** [comment] 2015-10-16 18:18
Ah...with resizing I can now reliably reproduce the issue on Win 7 FF.

I do not consider this a "blocking" issue. I would prefer not to publish with this issue present, but I consider it minor enough that it would be acceptable in terms of getting the sim out.

Regardless, seems worthy of investigation.

**Comment by jonathanolson** [comment] 2015-10-19 16:02
My best guess is a Firefox issue that may affect other sims (or may not) Graphical glitches that aren't lines or text/path quality changes might be related.

**Comment by jonathanolson** [comment] 2015-10-19 21:08
So far unable to reproduce on OS X Firefox.

**Comment by jonathanolson** [comment] 2015-10-19 21:14
Able to reproduce on FF 41.0.2, Win7. Will be looking for bug reports.

**Comment by ariel-phet** [comment] 2015-10-19 23:01
Yes, I have only seen on FF.

**Comment by jonathanolson** [comment] 2015-10-20 01:19
I haven't found a Mozilla bug for this after a lot of searching (SVG glitch and SVG artifact revealed only 2 issues each, so I was browsing through SVG ones).

I've been working making it 100% reproducible (on startup), so I can cut things out and create a minimal example that will trigger it for a bug report.

**Comment by pixelzoom** [comment] 2018-03-26 18:19
@phet-steele could you check whether this is still an issue with the new-and-improved Firefox Quantum (version 59+) ?

**Comment by phet-steele** [comment] 2018-04-27 17:33
@pixelzoom I followed the instructions scattered through this issue and didn't see a problem on Win 10 FF 59.0.2. Closing since this probably no longer needs attention.

**Closed as completed** 2018-04-27 17:34 UTC
Labels: type:bug, priority:4-low
