### ISSUE TITLE
typo in QA credits

### ISSUE THREAD

**Issue by samreid** [phetsims/hookes-law#28] opened 2015-10-08 17:00 UTC
From https://github.com/phetsims/bending-light/issues/255

"Brian Yoelin" should be "Bryan Yoelin".

**Comment by pixelzoom** [comment] 2015-10-08 17:35
Duplicate of https://github.com/phetsims/hookes-law/issues/26. This has already been fixed. Closing.

**Closed as completed by pixelzoom** 2015-10-08 17:35 UTC
