### ISSUE TITLE
Add an opaque rectangle behind values?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/hookes-law#34] opened 2015-10-19 21:12 UTC
At times, the energy value on the Energy Plot can overlap with the parabola. The overlap is most pronounced when k > 250N/m and Energy < 18J. I do not see this as a publication-blocking issue (and @ariel-phet agrees), as the value of the Energy is also clearly displayed on the bar graph. 

![image](https://cloud.githubusercontent.com/assets/8419308/10590778/cbd2691c-766f-11e5-9d51-3fa08e14b773.png)

One possible solution could be to add an opaque white rectangle behind the value. We've done something similar for the equipotential labels in Charges & Fields.
![image](https://cloud.githubusercontent.com/assets/8419308/10590739/995e234a-766f-11e5-9bcb-8aba4e6079d7.png)

My question is whether or not this is something that would be relatively easy to implement. If so, I would be curious to see if the energy plot becomes too obscured as the label becomes more visible.

Here's an example mockup with 50% opacity:
![image](https://cloud.githubusercontent.com/assets/8419308/10591224/52c56cb0-7672-11e5-95a8-f349fca6a4b5.png)

At 70% opacity, the value becomes more readable, but with an obviously faded chunk of the plot:
![image](https://cloud.githubusercontent.com/assets/8419308/10591282/9bac69ba-7672-11e5-80c5-ce2f50ebbaf4.png)

Assigning to @ariel-phet for feedback on the mocked up solution.

**Comment by ariel-phet** [comment] 2015-10-19 23:03
@pixelzoom - we do not consider this a blocking issue for publication, but when you return we will be curious if this is a small tweak or not. If so we might consider a minor maintenance release. If more invasive we will probably leave as is until a more major update is required.

**Comment by pixelzoom** [comment] 2015-10-21 14:11
Easy to implement.. It's already done for the displacement vector. Might just be an option that needs to turn on for the other vectors.

**Comment by pixelzoom** [comment] 2015-10-21 14:15
Ah, these values are not vectors. Still easy to do, using same technique as DisplacementVectorNode. About 30 minutes to implement.

**Comment by pixelzoom** [comment] 2015-10-27 16:48
@ariel-phet wrote:

> ... curious if this is a small tweak or not. If so we might consider a minor maintenance release. If more invasive we will probably leave as is until a more major update is required.

@arouinfar @ariel-phet Please advise on when you'd like this to be addressed.

**Comment by pixelzoom** [comment] 2016-01-21 18:11
This is an issue only with the energy (y-axis) value on the Energy Plot, since it's the only value that every overlaps with other parts of a plot.

**Comment by pixelzoom** [comment] 2016-01-21 18:49
Feature added in above commits, demonstrated in this dev version:

http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.1.0-dev.2/hookes-law_en.html

I used 70% opacity. Here's what it looks like in the scenario that was reported in https://github.com/phetsims/hookes-law/issues/34#issue-112234172.

![screenshot_112](https://cloud.githubusercontent.com/assets/3046552/12490823/cfebf5b8-c034-11e5-8e2c-7df6dfcf52fc.png)

@arouinfar please verify in the above dev version, let me know if you'd like to try a different opacity.

**Comment by arouinfar** [comment] 2016-01-21 19:00
Looks good to me! Thanks @pixelzoom.

**Comment by pixelzoom** [comment] 2016-01-21 19:08
I'm going to leave this open, labeled as "QA" so that we know to regression test for next published release.

**Comment by arouinfar** [comment] 2016-01-21 19:10
Oops! Sorry about that.

**Comment by pixelzoom** [comment] 2016-01-21 19:15
No problem @arouinfar, it's a new "convention" that I'm experimenting with, to keep track of what has changed since publication.

**Comment by arouinfar** [comment] 2016-01-27 21:15
Unassigning myself since this has been left open for future QA testing.

**Comment by pixelzoom** [comment] 2017-08-14 18:04
Decided to just go ahead and close this.

**Closed as completed by pixelzoom** 2017-08-14 18:04 UTC
